name: Playwright Smoke Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  smoke-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Test server startup
      run: |
        echo "Testing server startup..."
        timeout 30 bash -c 'until curl -f http://localhost:4000/; do sleep 1; done' || echo "Server not ready, but continuing with tests..."

    - name: Run Playwright smoke tests
      run: |
        echo "Starting Playwright smoke tests..."
        npx playwright test e2e/smoke.spec.js --reporter=html --verbose
      env:
        CI: true

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30

    - name: Comment PR with test results
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Check if test results exist
          const testResultsPath = 'test-results';
          if (fs.existsSync(testResultsPath)) {
            const files = fs.readdirSync(testResultsPath);
            const hasResults = files.length > 0;
            
            if (hasResults) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🧪 Playwright Smoke Tests Results
                
                ✅ Tests completed! Check the [workflow run](${context.payload.pull_request.html_url}/checks) for details.
                
                📊 **Artifacts Available:**
                - Playwright HTML Report
                - Test Results
                
                Download artifacts from the Actions tab to view detailed test results.`
              });
            }
          }
